server:
  port: ${eureka.consumer.server_1.port:9001}
spring:
  profiles:
    active: @profiles.active@
  application:
    #name: ${eureka.consumer.server_1.name:spring-cloud-eureak-consumer}
  zipkin:
    baseUrl: ${zipkin.server.host}:${zipkin.server.port:8890}

provider:
  server_1:
    name: ${eureka.provider.server_1.name}


#spring-cloud-eureak-provider:
  #ribbon:
    #ConnectTimeout: 500             #请求连接的超时时间
    #ReadTimeout: 1000               #请求处理的超时时间
    #OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    #MaxAutoRetriesNextServer: 3    #切换实例的重试次数
    #MaxAutoRetries: 3

feign:
  hystrix:
    enabled: true.

logging:
  config: classpath:config/logback-spring.xml
