zipkin:
  server:
   port: 9001
   host: http://localhost
eureka:
  host: localhost
  port: 8888
  provider:
    server_1:
      port: 10001
      name: spring-cloud-eureak-provider
  consumer:
    server_1:
          port: 10002
          name: spring-cloud-eureak-consumer

global:
  management:
    security:
      enabled: false
